  
matrix:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
before_install:
    - eval "${MATRIX_EVAL}"

language: C++

before_script:
  - bash install-dep-ubuntu.sh
  - bash setup.sh

script: cmake . && make && ./bin/requested_demo